name: Web and Mobile Test Automation Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  automation-tests:
    runs-on: windows-latest

    steps:
    # Pull the code from your repository into the runner
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Test Suite
        run: |
          pytest .\steps\ -k "web_ui" -v -s --alluredir=.\reports\allurereport
          

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always() # Ensures reports upload even if tests fail
        with:
          name: test-execution-reports
          path: reports/


