project_name: 'Oracle Cloud HCM'
##### Other project names ######
# Oracle Cloud HCM
# Mobile app name

environment: 'qa'
# Available options: dev / qa / staging / live

app_type: 'mobile'
# Available options: mobile / web

mobile_app_name: 'credit_sights'
# Available options: credit_sights, ismart_society

device: "emulator"
# Available options: samsung_A53

default_implicit_wait: 10
default_explicit_wait: 10


qa:
  base_url: https://iabfbv-test.fa.ocs.oraclecloud.com/fscmUI/faces/FuseWelcome
  
  valid_user: HCM_IMP
  valid_password: mightKnife364

  invalid_user: wrong_username
  invalid_password: wrong_password

staging:
  base_url: https://iabfbv-stg.fa.ocs.oraclecloud.com/fscmUI/faces/FuseWelcome
  
  valid_user: HCM_IMP_stage
  valid_password: mightKnife364_stage

  invalid_user: wrong_username
  invalid_password: wrong_password

devices:
  samsung_A53:
    platformName: 'Android'
    automationName: 'UiAutomator2'
    deviceName: 'adb-RZCTB15M0VF-RC2ens._adb-tls-connect._tcp'

  emulator:
    platformName: 'Android'
    automationName: 'UiAutomator2'
    deviceName: 'emulator-5554'


mobile_app_capabilities:
  credit_sights:
    appPackage: 'com.creditsights.reader.release'
    appium:fastReset: 'true'
    appium:noReset: 'false'

  book_my_show:
    appPackage: 'com.bt.bms'

  ismart_society:
    appPackage: 'com.technobliss.ismartsociety'

credit_sights:
  cr_email: 'testcsng@creditsights.com'
  cr_password: 'Park4701'